# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
# title: Title
title: AhBaku_Na        🌵
subtitle: sssssssssa
description: \HARU/ \HARU/ \HARU/ \\SABAKYU/ \\!!!/
keywords: 
author: swem
language: chinese
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: http://yoursite.com
url: https://senuren.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: cactus
# _config.yml
theme_config:
  colorscheme: white

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:senuren/senuren.github.io.git
  # repo: https://github.com/senuren/senuren.github.io.git
  # repo: https://senuren.github.io/
  branch: master

####L2D
# live2d:
#   enable: true
#   scriptFrom: local
#   pluginRootPath: live2dw/
#   pluginJsPath: lib/
#   pluginModelPath: assets/
#   tagMode: false
#   log: false
#   model:
#     use: live2d-widget-model-wanko
#   display:
#     position: right
#     width: 150
#     height: 300
#   mobile:
#     show: true
#   react:
#     opacity: 0.7

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  # enable: false
  pluginRootPath: live2dw/ # Root path of plugin to be on the site (Relative)
  pluginJsPath: lib/ # JavaScript path related to plugin's root (Relative)
  pluginModelPath: assets/ # Relative model path related to plugin's root (Relative)
  scriptFrom: local # Default
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # Your custom url
  tagMode: false # Whether only to replace live2d tag instead of inject to all pages
  log: false # Whether to show logs in console
  model:
    # use: live2d-widget-model-haru02
    # use: live2d-widget-model-haru01
    # use: live2d-widget-model-haru 
    # use: live2d-widget-model-haru/02
    use: live2d-widget-model-haru/01    
    # use: live2d-widget-model-hibiki
    # use: live2d-widget-model-hijiki
    # use: live2d-widget-model-z16
    # use: live2d-widget-model-unitychan
    # use: live2d-widget-model-tororo
    # use: live2d-widget-model-miku
    # use: live2d-widget-model-koharu
    # use: live2d-widget-model-izumi
    # use: live2d-widget-model-shizuku
    # use: live2d-widget-model-wanko # npm-module package name
    # use: wanko # folder name in (hexo base dir)/live2d_models/
    # use: ./wives/wanko # folder path relative to hexo base dir
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # Your custom url

  # Live2D
## https://github.com/xiazeyu/live2d-widget.js
## https://l2dwidget.js.org/docs/class/src/index.js~L2Dwidget.html#instance-method-init
# live2d:
  # model:
  #   scale: 1
  #   hHeadPos: 0.5
  #   vHeadPos: 0.618
  # display:
  #   superSample: 2
  #   width: 150
  #   height: 300
  #   position: right
  #   hOffset: 0
  #   vOffset: -20
  # mobile:
  #   show: true
  #   scale: 0.5
  # react:
  #   opacityDefault: 0.7
  #   opacityOnHover: 0.2